# Generated by Django 3.2.23 on 2023-12-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todoitem_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='is_done',
            field=models.BooleanField(default=True),
        ),
    ]
