# Generated by Django 4.2.8 on 2023-12-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todoitem_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
